name: user_social_profile
description: This package will display a developer's social profile information.
version: 1.0.5
homepage: https://github.com/mustafatahirhussein/user_social_profile
repository: https://github.com/mustafatahirhussein/user_social_profile
issue_tracker: https://github.com/mustafatahirhussein/user_social_profile/issues

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test:


flutter:

# To add assets to your package, add an assets section, like this:
#assets:
#   - assets/
